In [2]:
import numpy as np

In [2]:
data_original = np.load("e_spectrum_relics.npz")

In [3]:
data_original['CEvNS']

array([8.92738025e+04, 7.24821089e+03, 1.89479144e+03, 7.09425689e+02,
       3.05977230e+02, 1.38771544e+02, 6.34963142e+01, 2.87346663e+01,
       1.27261607e+01, 5.48180895e+00, 2.28769727e+00, 9.22707794e-01,
       3.59159319e-01, 1.34810976e-01, 4.87796055e-02, 1.70148066e-02,
       5.72258400e-03, 1.85654875e-03, 5.81291872e-04, 1.75759218e-04])

In [3]:
data_3 = np.load("3e.npz")
new_data_3 = {key: data_3[key] for key in data_3.files}
new_data_3['CEvNS'] = np.ones(len(new_data_3['CEvNS']))
new_data_3['CEvNS'][3] = 1e4
np.savez('3e.npz',**new_data_3)
data_3 = np.load("3e.npz")
data_3['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+04, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [4]:
data_4 = np.load("4e.npz")
new_data_4 = {key: data_4[key] for key in data_4.files}
new_data_4['CEvNS'] = np.ones(len(new_data_4['CEvNS']))
new_data_4['CEvNS'][4] = 1e4
np.savez('4e.npz',**new_data_4)
data_4 = np.load("4e.npz")
data_4['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+04, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [5]:
data_5 = np.load("5e.npz")
new_data_5 = {key: data_5[key] for key in data_5.files}
new_data_5['CEvNS'] = np.ones(len(new_data_5['CEvNS']))
new_data_5['CEvNS'][5] = 1e4
np.savez('5e.npz',**new_data_5)
data_5 = np.load("5e.npz")
data_5['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+04, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [6]:
data_6 = np.load("6e.npz")
new_data_6 = {key: data_6[key] for key in data_6.files}
new_data_6['CEvNS'] = np.ones(len(new_data_6['CEvNS']))
new_data_6['CEvNS'][6] = 1e4
np.savez('6e.npz',**new_data_6)
data_6 = np.load("6e.npz")
data_6['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+04, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [7]:
data_7 = np.load("7e.npz")
new_data_7 = {key: data_7[key] for key in data_7.files}
new_data_7['CEvNS'][7] = 1e4
np.savez('7e.npz',**new_data_7)
data_7 = np.load("7e.npz")
data_7['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+04,
       1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [9]:
data_8 = np.load("8e.npz")
new_data_8 = {key: data_8[key] for key in data_8.files}
new_data_8['CEvNS'][8] = 1e4
np.savez('8e.npz',**new_data_8)
data_8 = np.load("8e.npz")
data_8['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+04, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [10]:
data_9 = np.load("9e.npz")
new_data_9 = {key: data_9[key] for key in data_9.files}
new_data_9['CEvNS'][9] = 1e4
np.savez('9e.npz',**new_data_9)
data_9 = np.load("9e.npz")
data_9['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+04, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [11]:
data_10 = np.load("10e.npz")
new_data_10 = {key: data_10[key] for key in data_10.files}
new_data_10['CEvNS'][10] = 1e4
np.savez('10e.npz',**new_data_10)
data_10 = np.load("10e.npz")
data_10['CEvNS']

array([1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+04, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])