In [18]:
import numpy as np
import torch
import time

In [106]:
def CNN_output_vec_(out):
    event_Num = len(out)
    test_Num = event_Num
    # pos = np.zeros((test_Num, 2))
    # train_Num = 0
    print(event_Num)
    layer0 = [18, 17, 16, 15, 14]
    layer1 = [19, 40, 39, 38, 37, 13]
    layer2 = [20, 41, 56, 55, 54, 36, 12]
    layer3 = [21, 42, 57, 4, 5, 6, 53, 35, 11]
    layer4 = [22, 43, 58, 0, 1, 2, 3, 52, 34, 10]
    layer5 = [23, 44, 59, 7, 8, 9, 63, 51, 33]
    layer6 = [24, 45, 60, 61, 62, 50, 32]
    layer7 = [25, 46, 47, 48, 49, 31]
    layer8 = [26, 27, 28, 29, 30]
    layerlist = [layer0, layer1, layer2, layer3, layer4, layer5, layer6, layer7, layer8]

    xy_index = np.empty((64, 2), int)

    # 将对应的通道对应到9*9矩阵的位置
    for i in range(9):
        layeri = layerlist[i]
        id_x = int((10 - len(layeri)) / 2)
        for num in layeri:
            xy_index[num][0] = id_x
            xy_index[num][1] = i
            id_x += 1

    output_test = np.zeros((test_Num, 10, 10))
    # outpos_test = pos[train_Num : train_Num + test_Num]

    t = time.time()
    for i in range(test_Num):
        xj = xy_index[:, 0]
        yj = xy_index[:, 1]
        tmp = np.zeros((10, 10))
        # 归一化
        tmp[yj, xj] = out[i] / (np.sum(out[i][:64]) + 1e-8)
        output_test[i] = tmp
        if (i + 1) % 10000 == 0:
            print(i + 1, "/", test_Num, ",time:", time.time() - t)
            t = time.time()

    print("done of generating test files")

    output_test = torch.FloatTensor(output_test)
    # output_test为N*9*9矩阵，各个通道值按照对应关系填入对应坐标中,outpos_tes为空白的N*2位置矩阵
    return output_test


In [107]:
test_response = np.random.normal(loc = 10, scale = 2, size = (5000000,64))

In [108]:
t = time.time()
output_test_= CNN_output_vec_(test_response)
print(time.time() - t)

5000000
10000 / 5000000 ,time: 0.07729220390319824
20000 / 5000000 ,time: 0.07579302787780762
30000 / 5000000 ,time: 0.07683515548706055
40000 / 5000000 ,time: 0.07589387893676758
50000 / 5000000 ,time: 0.07573890686035156
60000 / 5000000 ,time: 0.07658934593200684
70000 / 5000000 ,time: 0.07549357414245605
80000 / 5000000 ,time: 0.07608628273010254
90000 / 5000000 ,time: 0.07681822776794434
100000 / 5000000 ,time: 0.07592082023620605
110000 / 5000000 ,time: 0.07605838775634766
120000 / 5000000 ,time: 0.07698822021484375
130000 / 5000000 ,time: 0.07636713981628418
140000 / 5000000 ,time: 0.07616806030273438
150000 / 5000000 ,time: 0.07639169692993164
160000 / 5000000 ,time: 0.0758657455444336
170000 / 5000000 ,time: 0.07559704780578613
180000 / 5000000 ,time: 0.07652783393859863
190000 / 5000000 ,time: 0.07554316520690918
200000 / 5000000 ,time: 0.07596158981323242
210000 / 5000000 ,time: 0.0789802074432373
220000 / 5000000 ,time: 0.07628178596496582
230000 / 5000000 ,time: 0.076339006

In [109]:
def CNN_output_vec(out):
    event_Num = len(out)
    test_Num = event_Num
    # pos = np.zeros((test_Num, 2))
    # train_Num = 0
    print(event_Num)
    layer0 = [18, 17, 16, 15, 14]
    layer1 = [19, 40, 39, 38, 37, 13]
    layer2 = [20, 41, 56, 55, 54, 36, 12]
    layer3 = [21, 42, 57, 4, 5, 6, 53, 35, 11]
    layer4 = [22, 43, 58, 0, 1, 2, 3, 52, 34, 10]
    layer5 = [23, 44, 59, 7, 8, 9, 63, 51, 33]
    layer6 = [24, 45, 60, 61, 62, 50, 32]
    layer7 = [25, 46, 47, 48, 49, 31]
    layer8 = [26, 27, 28, 29, 30]
    layerlist = [layer0, layer1, layer2, layer3, layer4, layer5, layer6, layer7, layer8]

    # xy_index = np.empty((64, 2), int)
    index = np.empty(64, int)

    # 将对应的通道对应到10*10矩阵的位置
    for i in range(9):
        layeri = layerlist[i]
        id_x = int((10 - len(layeri)) / 2)
        for num in layeri:
            index[num] = id_x + i * 10
            id_x += 1

    channel_eventID = np.arange(event_Num)[:, np.newaxis]

    output_test = np.zeros((event_Num, 100))
    output_test[channel_eventID, index] = test_response
    output_test = output_test.reshape(test_response.shape[0],10,10)
    output_test = output_test / np.sum(output_test,axis = (1,2)).reshape((event_Num, 1, 1)) 
    output_test = torch.FloatTensor(output_test)
    # output_test为N*9*9矩阵，各个通道值按照对应关系填入对应坐标中,outpos_tes为空白的N*2位置矩阵
    return output_test


In [110]:
t = time.time()
output_test= CNN_output_vec(test_response)
print(time.time() - t)

5000000
4.021116495132446


In [111]:
output_test[0],output_test_[0]

(tensor([[0.0000, 0.0000, 0.0211, 0.0125, 0.0186, 0.0140, 0.0161, 0.0000, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0140, 0.0106, 0.0200, 0.0128, 0.0194, 0.0164, 0.0000,
          0.0000],
         [0.0000, 0.0168, 0.0187, 0.0094, 0.0150, 0.0105, 0.0189, 0.0114, 0.0000,
          0.0000],
         [0.0135, 0.0157, 0.0176, 0.0143, 0.0167, 0.0184, 0.0174, 0.0145, 0.0116,
          0.0000],
         [0.0203, 0.0089, 0.0184, 0.0132, 0.0111, 0.0138, 0.0191, 0.0199, 0.0128,
          0.0149],
         [0.0145, 0.0140, 0.0165, 0.0169, 0.0180, 0.0164, 0.0178, 0.0163, 0.0146,
          0.0000],
         [0.0000, 0.0189, 0.0148, 0.0197, 0.0100, 0.0162, 0.0166, 0.0150, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0175, 0.0166, 0.0121, 0.0142, 0.0208, 0.0162, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0147, 0.0195, 0.0157, 0.0152, 0.0131, 0.0000, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         

In [112]:
output_test == output_test_

tensor([[[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

In [105]:
t = time.time()

layer0 = [18, 17, 16, 15, 14]
layer1 = [19, 40, 39, 38, 37, 13]
layer2 = [20, 41, 56, 55, 54, 36, 12]
layer3 = [21, 42, 57, 4, 5, 6, 53, 35, 11]
layer4 = [22, 43, 58, 0, 1, 2, 3, 52, 34, 10]
layer5 = [23, 44, 59, 7, 8, 9, 63, 51, 33]
layer6 = [24, 45, 60, 61, 62, 50, 32]
layer7 = [25, 46, 47, 48, 49, 31]
layer8 = [26, 27, 28, 29, 30]
layerlist = [layer0, layer1, layer2, layer3, layer4, layer5, layer6, layer7, layer8]

index = np.empty(64, int)

# 将对应的通道对应到10*10矩阵的位置
for i in range(9):
    layeri = layerlist[i]
    id_x = int((10 - len(layeri)) / 2)
    for num in layeri:
        index[num] = id_x + i * 10
        id_x += 1
        
test_response_event = np.arange(test_response.shape[0])[:, np.newaxis]

output_test = np.zeros((len(test_response), 100))

output_test[test_response_event, index] = test_response

output_test = output_test.reshape(test_response.shape[0],10,10)

output_test = output_test / np.sum(output_test,axis = (1,2)).reshape((test_response.shape[0], 1, 1)) 

output_test = torch.FloatTensor(output_test)

print(time.time() - t)

4.440267086029053


In [ ]:
test_response_event = np.arange(test_response.shape[0])[:, np.newaxis]
test_response_event.shape

(100000, 1)

In [72]:
test_response.shape

(100000, 64)

In [86]:
output_test.shape, output_test_.shape

(torch.Size([100000, 10, 10]), torch.Size([100000, 10, 10]))

In [92]:
output_test[0], output_test_[0]

(tensor([[0.0000, 0.0000, 0.0180, 0.0151, 0.0133, 0.0198, 0.0214, 0.0000, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0158, 0.0106, 0.0153, 0.0176, 0.0176, 0.0119, 0.0000,
          0.0000],
         [0.0000, 0.0125, 0.0116, 0.0175, 0.0159, 0.0108, 0.0171, 0.0149, 0.0000,
          0.0000],
         [0.0162, 0.0206, 0.0142, 0.0163, 0.0175, 0.0119, 0.0208, 0.0153, 0.0163,
          0.0000],
         [0.0194, 0.0150, 0.0181, 0.0133, 0.0145, 0.0132, 0.0202, 0.0144, 0.0135,
          0.0165],
         [0.0116, 0.0172, 0.0204, 0.0083, 0.0121, 0.0112, 0.0221, 0.0117, 0.0154,
          0.0000],
         [0.0000, 0.0194, 0.0118, 0.0159, 0.0183, 0.0129, 0.0116, 0.0190, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0167, 0.0181, 0.0164, 0.0090, 0.0165, 0.0162, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0182, 0.0168, 0.0165, 0.0195, 0.0134, 0.0000, 0.0000,
          0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         